### ISSUE TITLE
github build failed

### ISSUE THREAD

**Issue by symphonyh** [elotroalex/ed#16]
gem 'jekyll-scholar', '~>5.5.1' localhost   run is very good ,But github page build failed

**Comment by symphonyh** [comment]
github:  page build failed "recognized Liquid tag "
The problem lies in :<p>{% bibliography %}</p> and {% cite cesaire_discourse_2001 -r /bibliography.html %}
Where is the consultation problem? thank you!

**Comment by elotroalex** [comment]
hi @symphonyh. this error is caused because github pages runs on `--safe` mode. Did you run the rakefile in a `gh-pages` branch?

**Comment by symphonyh** [comment]
Has been resolved, the use of  **rake blog:punlish** , but the beginning can not be read to the CSS, Iremember the   _config.yml inside the *\* baseurl*\* set to Null character ‘ ’, do not write'/string'or their own definition of a string.        thank you!

**Comment by elotroalex** [comment]
@symphonyh out of curiosity, are you using the theme with Chinese characters? How is it displaying? Does it need more support for it? Did you have to install your own font?
