### ISSUE TITLE
Bundle and jekyll serve

### ISSUE THREAD

**Issue by mdlincoln** [elotroalex/ed#2]
IIUC if you are using bundler to help isolate your gem dependencies from other projects, I think it might be safer to use `bundle exec jekyll serve` instead of `jekyll serve`, so that Ruby will run jekyll based on the gem versions specified for `ed`.

Case in point: I foolishly barreled ahead with `jekyll serve` after running `bundle install`, and Ruby yelled at me because I have alternate versions of some of these gems already installed for my own blog (which uses the more restrictive `gh-pages` set of Jekyll gems). Using `bundle exec jekyll serve` quieted the complaints.

ps - this is an awesome framework!

**Comment by elotroalex** [comment]
Argh. Ye olde' bundle exec thingy. Thanks Matthew for the catch. Fixing in a sec.
